# Generated by Django 2.0.3 on 2018-03-30 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='type_of_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.ServiceType'),
        ),
    ]
