# Generated by Django 2.0.3 on 2018-04-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
