# Generated by Django 2.0.3 on 2018-03-27 21:46

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField((('basicHeader', wagtail.core.blocks.StructBlock((('backgroundImage', wagtail.images.blocks.ImageChooserBlock()), ('headline', wagtail.core.blocks.TextBlock()), ('caption', wagtail.core.blocks.TextBlock()), ('buttonLeft', wagtail.core.blocks.PageChooserBlock(required=True)), ('buttonRight', wagtail.core.blocks.PageChooserBlock(required=True))))), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('ItemCallout', wagtail.core.blocks.StructBlock((('headline', wagtail.core.blocks.TextBlock()), ('caption', wagtail.core.blocks.TextBlock()), ('item', wagtail.core.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.core.blocks.TextBlock()), ('caption', wagtail.core.blocks.TextBlock())))))))), blank=True),
        ),
    ]
